In [2]:
import torch
print(torch.__version__)

2.5.1+cu124


In [3]:
if torch.cuda.is_available():
    print("CUDA is available")
    print(torch.cuda.get_device_name(0))
else:
    print("CUDA is not available")

CUDA is available
NVIDIA GeForce RTX 3050 Laptop GPU


In [4]:
a = torch.empty(2, 3)

In [5]:
type(a)

torch.Tensor

In [6]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
torch.manual_seed(42)

In [9]:
torch.rand(2, 3) # random numbers from 0 to 1

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [10]:
torch.tensor([[2, 3, 4],[1,2,3]])

tensor([[2, 3, 4],
        [1, 2, 3]])

In [11]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [12]:
x = torch.full((3,2),4)

In [13]:
a.shape

torch.Size([2, 3])

In [14]:
x.shape

torch.Size([3, 2])

In [15]:
a.dtype

torch.float32

In [16]:
x.dtype

torch.int64